### PR TITLE
Ruby Mode

### PR DESCRIPTION
**Pull request by mbriggs**
First of all, I absolutely love this extension :)

In ruby, its very common to have blocks within blocks within blocks (if you don't know the language, they are basically like lambdas), so I added an expansion for them. Also, the function level expansion wasn't working, so I added that too.

There is a bug with the block expansion, where if you have two blocks which are contained within an outer block, and are within the bottom block, it will completely ignore the outer block when expanding. I'll try to figure it out (a bit of an elisp noob), but what I have covers the 99% case

### CODE REVIEW

**Comment by mbriggs** [comment]
what ever happened with this? I mailed the papers twice to the FSF... I noticed in another issue you were still trying to get ER into emacs core, I would be willing to try again if it would help you out

**Comment by magnars** [comment]
Hi Matt!

It took 19 months to get all the contribution papers signed (except yours,
which never arrived) - at which point I had lost what energy I had in me to
get this into Emacs core. It's a sad story. Thanks for getting back to me
tho.

- Magnar

**Comment by mbriggs** [comment]
i know its too little, and WAY too late, but FWIW

[Briggs.1092467.EMACS.pdf](https://github.com/magnars/expand-region.el/files/178116/Briggs.1092467.EMACS.pdf)

Just want to apologize about this again. My boss at the time was very resistant to signing, and I didnt think I could get him to do it again. I also thought the FSF could find the document, or worst case, that what i did wasnt rocket science and could be removed and reimplemented by someone who hadnt seen it. I know i screwed you over here, and I feel very bad about it.

**Comment by magnars** [comment]
Hey Matt. Don't feel bad, mate. It was a bit frustrating at the time, but that's all. It taught me a lesson about the difference between open source and free software, something I had never really considered before. I'm glad you got the papers to FSF in the end. :)

**Pull request merged**
