### PR TITLE
Replace deprecated 'cl package by 'cl-lib

### PR DESCRIPTION
**Pull request by thisch**

### CODE REVIEW

**Comment by magnars** [comment]
I take it this is failing because it's checking against older emacsen. When did `cl-lib` become the default?

**Comment by thisch** [comment]
I don't know when it became the default. I only know that it was marked as obsolete beginning with emacs-27. Since cl-lib should be available for all emacs versions tested by travis in this project, I don't understand why they fail.

**Comment by magnars** [comment]
I have a feeling the breaking build is not related to this change. I'll take a look at the tests tomorrow.

**Comment by thisch** [comment]
You are right, my change is not related to this PR. I've just verified this locally.

**Comment by thisch** [comment]
Hi @magnars. friendly ping.

**Comment by magnars** [comment]
I got derailed by looking at including expand-region in Emacs. Let's get this in.

**Pull request merged**
