### PR TITLE
Add expansion support for Ensime Mode

### PR DESCRIPTION
**Pull request by lunaryorn**
Adds support for Ensime Mode, by hooking Ensime's syntactic expansion feature into Expand Region.

/cc @fommil

### CODE REVIEW

**Comment by fommil** [comment]
Fantastic! Ping me when its on MELPA and I'll tweet it.

**Comment by lunaryorn** [comment]
@fommil You can just subscribe to this ticket, can't you?

**Comment by fommil** [comment]
Ah yes that's true.

**Comment by lunaryorn** [comment]
@fommil I'll open a PR for Ensime tomorrow, as copyright assignment apparently stand in the way of merging this one.  I'm sorry for the hassle, I didn't know this.

**Comment by fommil** [comment]
If you contribute to ensime-emacs can you make this an optional dependency? See how we do that for ensime-autacomplete (might be in a PR waiting for merge). Reducing dep list is a high priority right now.

**Comment by lunaryorn** [comment]
Sure, that was my plan.  It's easy enough 😎

**Comment by lunaryorn** [comment]
@fommil I think it's probably even better to just put this code into a separate package on MELPA, e.g. `ensime-expand-region` or so, to prevent an expand-region dependency from creeping into Ensime right away.  What do you think?

**Comment by fommil** [comment]
OK, that works too! In a couple of years, we can just fold it into ENSIME proper as all deps will be Emacs core. Make sure you add it to the wiki, we should probably create a "favourite Scala modes" page with stuff like this and some other useful .emacs config.

**Comment by lunaryorn** [comment]
@fommil To what wiki?  That of Ensime Emacs?  If you want I can also use a repo within the Ensime org, for better discoverability of the new extension…

**Comment by fommil** [comment]
Yup. I'm actually OK with you dropping it into ensime-emacs and then people need to manually install expand-region if they want to use it. Best that we are consistent with how we handle optional modules. I'm traveling for a day but if you raise a PR I'll show you what needs to be done to make it optional.

**Comment by lunaryorn** [comment]
Ok, I'll knock together a PR for Ensime Emacs, and wait for your review.

**Comment by lunaryorn** [comment]
@fommil See https://github.com/ensime/ensime-emacs/issues/263

**Pull request closed without merging**
