### PR TITLE
Revert "Bugfix: save-mark-and-excursion does not exist until E25.1"

### PR DESCRIPTION
**Pull request by magnars**
Reverts magnars/expand-region.el#177

### CODE REVIEW

**Comment by jasonm23** [comment]
Why is this defined as a macro when a defun will do?

PSA don't unnecessarily defmacro.

**Comment by magnars** [comment]
Because it has to be a macro.

**Comment by jasonm23** [comment]
It also works as a defun... So "has to"? Why?

**Comment by magnars** [comment]
> It also works as a defun...

It really doesn't. `save-excursion` has to wrap the execution of its body.

**Comment by jasonm23** [comment]
I was patching the problem locally for a while now, and I used a defun to do it.  It works.

**Pull request merged**
